# Generated by Django 5.0 on 2023-12-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramFeeds',
        ),
        migrations.DeleteModel(
            name='SocialNetworks',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
